version: '3.3'
services:
  #The ss14 map server container doesn't support https on its own. Please use a reverse proxy
  ss14mapserver:
    build:
      context: ./
      dockerfile: SS14.MapServer/Dockerfile
    volumes:
      - ./appsettings.yaml:/app/appsettings.yaml #This is a file
      - ./private-key.pem:/app/private-key.pem #
      - ./files:/app/data
      - ./build:/app/build
    ports:
      - 5218:80 #Replace 5218 with the port you need
    # Disables core dumps to prevent maprenderer crashes from filling up your hard drive with over a gigabyte per dump
    ulimits:
      core:
        hard: 0
        soft: 0
  map_database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres #Replace postgres with a randomly generated password
    volumes:
      - ./data:/var/lib/postgresql/data
